gpu_id: 1
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'hcrn_havf_exp_middle_vcrn'
level: 'middle-vcrn'
fuse_type: 'concat'
useAudio: True

train:
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 50
  vision_dim: 2048
  audio_dim: 2048
  word_dim: 300
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: True

dataset:
  name: 'avqa'
  question_type: 'none'
  data_dir: '../../data/feats'
  save_dir: 'out/hcrn_havf_exp_middle_vcrn'
  ans_count: 4
